-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://github.com/pgadmin-org/pgadmin4/issues/new/choose if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public."Colab"
(
    id_colab integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    nome character(20) COLLATE pg_catalog."default",
    nome_usuario character(20) COLLATE pg_catalog."default",
    senha character(20) COLLATE pg_catalog."default",
    CONSTRAINT "Colab_pkey" PRIMARY KEY (id_colab),
    CONSTRAINT "Colab_nome_usuario_key" UNIQUE (nome_usuario)
);

CREATE TABLE IF NOT EXISTS public."Leitor"
(
    id_leitor integer NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    nome character varying(90) COLLATE pg_catalog."default",
    telefone character varying(90) COLLATE pg_catalog."default",
    email character varying(90) COLLATE pg_catalog."default",
    cpf character varying(90) COLLATE pg_catalog."default" NOT NULL,
    identidade character varying(90) COLLATE pg_catalog."default" NOT NULL,
    cep character varying(90) COLLATE pg_catalog."default",
    escolaridade character varying(90) COLLATE pg_catalog."default",
    data_nascimento character varying(90) COLLATE pg_catalog."default",
    endereco character varying(90) COLLATE pg_catalog."default",
    data_cadastro character varying(90) COLLATE pg_catalog."default",
    CONSTRAINT "Leitor_pkey" PRIMARY KEY (id_leitor),
    CONSTRAINT "Leitor_id_leitor_identidade_cpf_key" UNIQUE (id_leitor, identidade, cpf)
);

CREATE TABLE IF NOT EXISTS public."Livros"
(
    id_livro integer NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    n_tombo character varying(90) COLLATE pg_catalog."default" NOT NULL,
    isbn character varying(90) COLLATE pg_catalog."default" NOT NULL,
    editora character varying(90) COLLATE pg_catalog."default",
    ano_edicao character varying(90) COLLATE pg_catalog."default",
    classificacao character varying(200) COLLATE pg_catalog."default",
    n_folhas character varying(90) COLLATE pg_catalog."default",
    titulo_livro character varying(90) COLLATE pg_catalog."default",
    autor character varying(90) COLLATE pg_catalog."default",
    volume character varying(90) COLLATE pg_catalog."default",
    data_cadastro character varying(90) COLLATE pg_catalog."default",
    assunto character varying(90) COLLATE pg_catalog."default",
    CONSTRAINT "Livros_pkey" PRIMARY KEY (id_livro),
    CONSTRAINT "Livros_id_livro_isbn_n_tombo_key" UNIQUE (id_livro, isbn, n_tombo)
);
END;